services:
    loevgaard_economic.client:
        class: GuzzleHttp\Client
        arguments:
            -
                base_uri: "%loevgaard_economic.base_uri%"
                headers:
                    X-AppSecretToken: "%loevgaard_economic.app_secret_token%"
                    X-AgreementGrantToken: "%loevgaard_economic.agreement_grant_token%"
                    Content-Type: application/json